spring:
  flyway:
    schemas: people
    validate-migration-naming: true
  datasource:
    username: postgres
    password: root123.
    url: jdbc:postgresql://localhost:5432/people
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect
logging:
  level:
    sql: debug